/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.xprodswings.principal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 77011-26-10
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        this.setTitle("Xprod gestion des clients");
        setLocationRelativeTo(null); // pour Centrer le contenu de ma fenetre
        tableUpdate(); // Mettre a jour la table des produits 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPRENOM = new javax.swing.JTextField();
        txtNOM = new javax.swing.JTextField();
        txtADRESSE = new javax.swing.JTextField();
        txtCODEPOSTAL = new javax.swing.JTextField();
        txtVILLE = new javax.swing.JTextField();
        txtTEL = new javax.swing.JTextField();
        txtPAYS = new javax.swing.JTextField();
        txtEMAIL = new javax.swing.JTextField();
        txtMOBILE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCLIENT = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAJOUTER = new javax.swing.JButton();
        btnMODIFIER = new javax.swing.JButton();
        btnSUPPRIMER = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAddCommande = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemAddFournisseur = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemAddProduit = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemGestionUtilisateurs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Infos Client"));

        jLabel1.setText("PRENOM");

        jLabel2.setText("NOM");

        jLabel3.setText("ADRESSE");

        jLabel4.setText("CODE POSTAL");

        jLabel5.setText("VILLE");

        jLabel6.setText("TEL");

        jLabel7.setText("PAYS");

        jLabel8.setText("EMAIL");

        jLabel9.setText("MOBILE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMOBILE, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                    .addComponent(txtEMAIL, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                    .addComponent(txtPAYS)
                    .addComponent(txtTEL)
                    .addComponent(txtVILLE)
                    .addComponent(txtPRENOM)
                    .addComponent(txtNOM)
                    .addComponent(txtADRESSE)
                    .addComponent(txtCODEPOSTAL)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPRENOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtADRESSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCODEPOSTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtVILLE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPAYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMOBILE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("CLIENT");

        tableCLIENT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDCLIENT", "PRENOM", "NOM", "ADRESSE", "CODE POSTAL", "VILLE", "TEL", "PAYS", "EMAIL", "MOBILE"
            }
        ));
        tableCLIENT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCLIENTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCLIENT);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        btnAJOUTER.setBackground(new java.awt.Color(51, 255, 0));
        btnAJOUTER.setText("AJOUTER");
        btnAJOUTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAJOUTERActionPerformed(evt);
            }
        });

        btnMODIFIER.setBackground(new java.awt.Color(51, 255, 0));
        btnMODIFIER.setText("MODIFIER");
        btnMODIFIER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMODIFIERActionPerformed(evt);
            }
        });

        btnSUPPRIMER.setBackground(new java.awt.Color(51, 255, 0));
        btnSUPPRIMER.setText("SUPPRIMER");
        btnSUPPRIMER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUPPRIMERActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSUPPRIMER)
                    .addComponent(btnAJOUTER, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMODIFIER, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnAJOUTER)
                .addGap(129, 129, 129)
                .addComponent(btnMODIFIER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(btnSUPPRIMER)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("ADMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(774, 774, 774)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Commande");

        jMenuItemAddCommande.setText("Ajouter une commande");
        jMenuItemAddCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCommandeActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAddCommande);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Fournisseur");

        jMenuItemAddFournisseur.setText("Ajouter un fournisseur");
        jMenuItemAddFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddFournisseurActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAddFournisseur);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Produits");

        jMenuItemAddProduit.setText("Ajouter un produit");
        jMenuItemAddProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddProduitActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemAddProduit);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Login");

        jMenuItemLogin.setText("Se Connecter");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemLogin);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Utilisateur");

        jMenuItemGestionUtilisateurs.setText("Gestion des utilisateurs");
        jMenuItemGestionUtilisateurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionUtilisateursActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemGestionUtilisateurs);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        Connection con;
        PreparedStatement pst ;
private void tableUpdate(){
        int cpt;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/xprod", "root","");
            pst=con.prepareStatement("SELECT * FROM `client`");
            ResultSet rs = null;
            try {
                rs = pst.executeQuery();
            } catch (SQLException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
            ResultSetMetaData rsmd = rs.getMetaData();
            cpt= rsmd.getColumnCount();
            DefaultTableModel dtm =(DefaultTableModel)tableCLIENT.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
                Vector vect = new Vector();
            
                 for (int i=1;i<= cpt; i++){
                    vect.add(rs.getString("IDCLIENT"));
                    vect.add(rs.getString("PRENOM"));
                    vect.add(rs.getString("NOM"));
                    vect.add(rs.getString("ADRESSE"));
                    vect.add(rs.getString("CP"));
                    vect.add(rs.getString("VILLE"));
                    vect.add(rs.getString("PAYS"));
                    vect.add(rs.getString("TEL"));
                    vect.add(rs.getString("MOBILE"));
                    vect.add(rs.getString("EMAIL"));
                }
                dtm.addRow(vect);
            }
             
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    private void btnAJOUTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAJOUTERActionPerformed
        String prenomClient = txtPRENOM.getText();
        String nomClient = txtNOM.getText();
        String adresseClient= txtADRESSE.getText();
        String codepostalClient = txtCODEPOSTAL.getText();
        String villeClient = txtVILLE.getText();
        String telClient = txtTEL.getText();
        String paysClient = txtPAYS.getText();
        String emailClient = txtEMAIL.getText();
        String mobileClient = txtMOBILE.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // Enregistrer le Driver JDBC
            con = DriverManager.getConnection("jdbc:mysql://localhost/xprod", "root", "");
            pst=con.prepareStatement("INSERT INTO `client` (`PRENOM`, `NOM`, `ADRESSE`, `CP`, `VILLE`, `PAYS`, `TEL`, `MOBILE`, `EMAIL`) VALUES (?,?,?,?,?,?,?,?,?)");    
            
            pst.setString(1, prenomClient);
            pst.setString(2, nomClient);
            pst.setString(3, adresseClient);
            pst.setString(4, codepostalClient);
            pst.setString(5, villeClient);
            pst.setString(6, telClient);
            pst.setString(7, paysClient);
            pst.setString(8, emailClient);
            pst.setString(9, mobileClient);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Le client a bien été ajouté");
            
            // Je vide le contenu des champs remplis 
            txtPRENOM.setText("");
            txtNOM.setText("");
            txtADRESSE.setText("");
            txtCODEPOSTAL.setText("");
            txtVILLE.setText("");
            txtTEL.setText("");
            txtPAYS.setText("");
            txtEMAIL.setText("");
            txtMOBILE.setText("");
            tableUpdate();
         
        } catch (SQLException ex) {
            Logger.getLogger(XprodDesktopClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(XprodDesktopClient.class.getName()).log(Level.SEVERE, null, ex);
        }                          // TODO add your handling code here:
    }//GEN-LAST:event_btnAJOUTERActionPerformed

    private void btnMODIFIERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMODIFIERActionPerformed
        //Modification    
        DefaultTableModel dtm =(DefaultTableModel)tableCLIENT.getModel();
        try{    
            int selectedIndex = tableCLIENT.getSelectedRow();
            int idClient = Integer.parseInt(dtm.getValueAt(selectedIndex,0).toString());
            String prenomClient = txtPRENOM.getText();
            String nomClient = txtNOM.getText();
            String adresseClient= txtADRESSE.getText();
            String codepostalClient = txtCODEPOSTAL.getText();
            String villeClient = txtVILLE.getText();
            String telClient = txtTEL.getText();
            String paysClient = txtPAYS.getText();
            String emailClient = txtEMAIL.getText();
            String mobileClient = txtMOBILE.getText();


            Class.forName("com.mysql.cj.jdbc.Driver"); // Enregistrer le Driver JDBC
            con = DriverManager.getConnection("jdbc:mysql://localhost/xprod", "root", "");
            pst = con.prepareStatement("update client set PRENOM=?,NOM=?,ADRESSE=?,CP=?,VILLE=?,TEL=?,PAYS=?,EMAIL=?,MOBILE=?where IDCLIENT=?");
            pst.setString(1, prenomClient);
            pst.setString(2, nomClient);
            pst.setString(3, adresseClient);
            pst.setString(4, codepostalClient);
            pst.setString(5, villeClient);
            pst.setString(6, telClient);
            pst.setString(7, paysClient);
            pst.setString(8, emailClient);
            pst.setString(9, mobileClient);
            pst.setInt(10, idClient);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Le client a bien été modifié");
           
            // Je vide le contenu des champs remplis 
            txtPRENOM.setText("");
            txtNOM.setText("");
            txtADRESSE.setText("");
            txtCODEPOSTAL.setText("");
            txtVILLE.setText("");
            txtTEL.setText("");
            txtPAYS.setText("");
            txtEMAIL.setText("");
            txtMOBILE.setText("");
            tableUpdate();
         

        }catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }//GEN-LAST:event_btnMODIFIERActionPerformed

    private void tableCLIENTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCLIENTMouseClicked
// Pour selectionner  les informations d'un champ
        DefaultTableModel dtm =(DefaultTableModel)tableCLIENT.getModel();
        int selectedIndex = tableCLIENT.getSelectedRow();

        txtPRENOM.setText(dtm.getValueAt(selectedIndex, 1).toString());
        txtNOM.setText(dtm.getValueAt(selectedIndex, 2).toString());
        txtADRESSE.setText(dtm.getValueAt(selectedIndex, 3).toString());
        txtCODEPOSTAL.setText(dtm.getValueAt(selectedIndex, 4).toString());
        txtVILLE.setText(dtm.getValueAt(selectedIndex, 5).toString());
        txtTEL.setText(dtm.getValueAt(selectedIndex, 6).toString());
        txtPAYS.setText(dtm.getValueAt(selectedIndex, 7).toString());
        txtEMAIL.setText(dtm.getValueAt(selectedIndex, 8).toString());
        txtMOBILE.setText(dtm.getValueAt(selectedIndex, 9).toString());
    }//GEN-LAST:event_tableCLIENTMouseClicked

    private void btnSUPPRIMERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUPPRIMERActionPerformed
       
        DefaultTableModel dtm =(DefaultTableModel)tableCLIENT.getModel();
        int selectedIndex = tableCLIENT.getSelectedRow();
            
        int idProduit = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer cette donnée","Attention",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            try {
                Class.forName("com.mysql.cj.jdbc.Driver"); // Enregistrer le Driver JDBC
                con = DriverManager.getConnection("jdbc:mysql://localhost/xprod", "root", "");
                pst = con.prepareStatement("delete from client where IDCLIENT=?");
            
                pst.setInt(1, idProduit);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Le client a bien été supprimé");
                // Je vide le contenu des champs remplis 
               txtPRENOM.setText("");
               txtNOM.setText("");
               txtADRESSE.setText("");
               txtCODEPOSTAL.setText("");
               txtVILLE.setText("");
               txtTEL.setText("");
               txtPAYS.setText("");
               txtEMAIL.setText("");
               txtMOBILE.setText("");
               tableUpdate();
            
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSUPPRIMERActionPerformed

    private void jMenuItemAddCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCommandeActionPerformed
        CommandeAdmin newProd = new CommandeAdmin();
        newProd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemAddCommandeActionPerformed

    private void jMenuItemAddFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddFournisseurActionPerformed
        FournisseurAdmin newFour = new FournisseurAdmin();
        newFour.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemAddFournisseurActionPerformed

    private void jMenuItemAddProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddProduitActionPerformed
        XprodDesktopAdministrateur newProd = new XprodDesktopAdministrateur();
        newProd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemAddProduitActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        Login newLog = new Login();
        newLog.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemGestionUtilisateursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionUtilisateursActionPerformed
        RegisterAdmin newReg = new RegisterAdmin();
        newReg.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestionUtilisateursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAJOUTER;
    private javax.swing.JButton btnMODIFIER;
    private javax.swing.JButton btnSUPPRIMER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAddCommande;
    private javax.swing.JMenuItem jMenuItemAddFournisseur;
    private javax.swing.JMenuItem jMenuItemAddProduit;
    private javax.swing.JMenuItem jMenuItemGestionUtilisateurs;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCLIENT;
    private javax.swing.JTextField txtADRESSE;
    private javax.swing.JTextField txtCODEPOSTAL;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtMOBILE;
    private javax.swing.JTextField txtNOM;
    private javax.swing.JTextField txtPAYS;
    private javax.swing.JTextField txtPRENOM;
    private javax.swing.JTextField txtTEL;
    private javax.swing.JTextField txtVILLE;
    // End of variables declaration//GEN-END:variables
}
