/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.xprodswing.principal;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Najat
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Fournisseur
     */
    public Client() {
        initComponents();
       this.setTitle("Client: Liste des clients");
       setLocationRelativeTo(null); //pour centrerle contenu de ma fenêtre
       tableUpdate(); //Mettre à jour la table des fournisseurs }
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNOMCLIENT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtADRESSECLIENT = new javax.swing.JTextField();
        txtPAYSCLIENT = new javax.swing.JTextField();
        txtVILLECLIENT = new javax.swing.JTextField();
        txtMOBILECLIENT = new javax.swing.JTextField();
        txtEMAILCLIENT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPRENOMCLIENT = new javax.swing.JTextField();
        txtCODEPOSTALCLIENT = new javax.swing.JTextField();
        btnADDClient = new javax.swing.JButton();
        btnMODIFIER1 = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableClients = new javax.swing.JTable();
        txtTELCLIENT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemAddFournisseur = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemADDCOMMANDE = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 204, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("LISTE DES CLIENTS");

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom :");

        txtNOMCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMCLIENTActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adresse");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ville :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Code Postal :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pays :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mobile");

        txtADRESSECLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtADRESSECLIENTActionPerformed(evt);
            }
        });

        txtPAYSCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAYSCLIENTActionPerformed(evt);
            }
        });

        txtVILLECLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVILLECLIENTActionPerformed(evt);
            }
        });

        txtMOBILECLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMOBILECLIENTActionPerformed(evt);
            }
        });

        txtEMAILCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEMAILCLIENTActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Prénom :");

        txtPRENOMCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPRENOMCLIENTActionPerformed(evt);
            }
        });

        txtCODEPOSTALCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCODEPOSTALCLIENTActionPerformed(evt);
            }
        });

        btnADDClient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnADDClient.setForeground(new java.awt.Color(51, 153, 255));
        btnADDClient.setText("AJOUTER");
        btnADDClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDClientActionPerformed(evt);
            }
        });

        btnMODIFIER1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMODIFIER1.setForeground(new java.awt.Color(51, 153, 255));
        btnMODIFIER1.setText("Modifier");
        btnMODIFIER1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMODIFIER1ActionPerformed(evt);
            }
        });

        btnDELETE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDELETE.setForeground(new java.awt.Color(51, 153, 255));
        btnDELETE.setText("Supprimer");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(51, 153, 255));

        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM", "PRENOM", "ADRESSE", "CP", "VILLE", "PAYS", "TEL", "MOBILE", "EMAIL"
            }
        ));
        tableClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableClients);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        txtTELCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTELCLIENTActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tel:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCODEPOSTALCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEMAILCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTELCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(txtPRENOMCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtPAYSCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtVILLECLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMOBILECLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtADRESSECLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNOMCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnADDClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMODIFIER1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDELETE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNOMCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPRENOMCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(btnADDClient))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtADRESSECLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtCODEPOSTALCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(btnMODIFIER1)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtVILLECLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtPAYSCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtTELCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDELETE)
                    .addComponent(txtMOBILECLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEMAILCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(621, 621, 621)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu6.setText("Fournisseur");

        jMenuItemAddFournisseur.setText("Ajouter un fournisseur");
        jMenuItemAddFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddFournisseurActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemAddFournisseur);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Commande");

        jMenuItemADDCOMMANDE.setText("Ajouter une commande");
        jMenuItemADDCOMMANDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemADDCOMMANDEActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemADDCOMMANDE);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Utilisateurs");

        jMenuItem3.setText("Ajouter un utilisateur");
        jMenu8.add(jMenuItem3);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNOMCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMCLIENTActionPerformed

    private void txtADRESSECLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtADRESSECLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtADRESSECLIENTActionPerformed

    private void txtPAYSCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAYSCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAYSCLIENTActionPerformed

    private void txtVILLECLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVILLECLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVILLECLIENTActionPerformed

    private void txtMOBILECLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMOBILECLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMOBILECLIENTActionPerformed

    private void txtEMAILCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEMAILCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEMAILCLIENTActionPerformed

    private void txtPRENOMCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPRENOMCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRENOMCLIENTActionPerformed

    private void txtCODEPOSTALCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCODEPOSTALCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCODEPOSTALCLIENTActionPerformed

    private void btnADDClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDClientActionPerformed
        // Je récupère les infos  de mes champs de texte
        String nomClient = txtNOMCLIENT.getText();
          String prenomClient = txtPRENOMCLIENT.getText();
          String adresseClient = txtADRESSECLIENT.getText();
          String villeClient = txtVILLECLIENT.getText();
          String codePostalClient = txtCODEPOSTALCLIENT.getText();
          String paysClient = txtPAYSCLIENT.getText();
          String mobileClient = txtMOBILECLIENT.getText();
              String telClient = txtTELCLIENT.getText();
         String emailClient = txtEMAILCLIENT.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");  //Enregistrer le driver JDBC dans ma classe
            con = DriverManager.getConnection("jdbc:mysql://localhost/xproddb", "root","");

            System.out.println("connection réussie");
            pst = con.prepareStatement("INSERT INTO clients(NOMCLIENT, PRENOMCLIENT, ADRESSECLIENT, VILLECLIENT, CODEPOSTALCLIENT, PAYSCLIENT, EMAILCLIENT,MOBILECLIENT,TELCLIENT)"
                + "VALUES (?,?,?,?,?,?,?,?,?)");

            pst.setString(1, nomClient);
            pst.setString(2, prenomClient);
            pst.setString(3, adresseClient);
            pst.setString(4, villeClient);
            pst.setString(5, codePostalClient);
            pst.setString(6, paysClient );
             pst.setString(7, telClient);
              pst.setString(8, mobileClient);
                pst.setString(9, emailClient);
            
            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Données enregistrées");

            //Je vide le contenu des champs remplis
          
             txtNOMCLIENT.setText("");
             txtPRENOMCLIENT.setText("");
             txtADRESSECLIENT.setText("");
             txtVILLECLIENT.setText("");            
             txtCODEPOSTALCLIENT.setText("");   
             txtPAYSCLIENT.setText("");        
             txtMOBILECLIENT.setText("");
                  txtTELCLIENT.setText("");   
                    txtEMAILCLIENT.setText("");

            //actualisation ma table
            tableUpdate();
            //JOptionPane.showMessageDialog(this, "Données enregistrées");

        }catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);}

        catch (ClassNotFoundException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnADDClientActionPerformed

    private void btnMODIFIER1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMODIFIER1ActionPerformed

        //Modification
        DefaultTableModel dtm =(DefaultTableModel)tableClients.getModel();
        
   
             try{
           int selectedIndex = tableClients.getSelectedRow();
        int idClient = Integer.parseInt(dtm.getValueAt(selectedIndex,0).toString());
        
        String nomClient =   txtNOMCLIENT.getText();
         String prenomClient =   txtPRENOMCLIENT.getText();
        String adresseClient = txtADRESSECLIENT.getText();
        String codePostalClient = txtCODEPOSTALCLIENT.getText();
        String villeClient = txtVILLECLIENT.getText();
        String paysClient = txtPAYSCLIENT.getText();
        String telClient = txtTELCLIENT.getText();
        String emailClient = txtEMAILCLIENT.getText();
        String mobileClient = txtMOBILECLIENT.getText();

     
            // int selectedIndex = tableFournisseurs.getSelectedRow();

            Class.forName("com.mysql.cj.jdbc.Driver"); // Enregistrer le Driver JDBC
            con = DriverManager.getConnection("jdbc:mysql://localhost/xproddb", "root", "");

            pst =con.prepareStatement("update  clients set NOMCLIENT=?,PRENOMCLIENT=?,ADRESSECLIENT=?, VILLECLIENT=?, CODEPOSTALCLIENT=?, PAYSCLIENT=?, TELCLIENT=?, MOBILECLIENT=?, EMAILCLIENT=? where IDCLIENT=?" ) ;

             pst.setString(1, nomClient);
            pst.setString(2, prenomClient);
            pst.setString(3, adresseClient);
            pst.setString(4, villeClient);
            pst.setString(5, codePostalClient);
            pst.setString(6, paysClient );
            pst.setString(7, telClient);
            pst.setString(8, mobileClient);
            pst.setString(9, emailClient);
               pst.setInt(10, idClient);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"ca a marché");

            // Je vide le contenu des champs remplis
             txtNOMCLIENT.setText("");
             txtPRENOMCLIENT.setText("");
             txtADRESSECLIENT.setText("");
             txtCODEPOSTALCLIENT.setText("");   
              txtVILLECLIENT.setText("");   
              txtPAYSCLIENT.setText("");
               txtTELCLIENT.setText("");
               txtMOBILECLIENT.setText("");
               txtEMAILCLIENT.setText("");
        

            tableUpdate();        // TODO modifier your handling code here:

        }catch (ClassNotFoundException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMODIFIER1ActionPerformed

    private void txtTELCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTELCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTELCLIENTActionPerformed

    private void jMenuItemADDCOMMANDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemADDCOMMANDEActionPerformed
        // TODO add your handling code here:
         Commande newCommande = new Commande();
          newCommande.setVisible(true);
    }//GEN-LAST:event_jMenuItemADDCOMMANDEActionPerformed

    private void jMenuItemAddFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddFournisseurActionPerformed
        // TODO add your handling code here:
           Fournisseur newFour = new Fournisseur();
        newFour.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemAddFournisseurActionPerformed

    private void tableClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientsMouseClicked
        // TODO add your handling code here:
            // pour sélectionner les informations d'un champs
            DefaultTableModel dtm =(DefaultTableModel)tableClients.getModel();
            int selectedIndex = tableClients.getSelectedRow();
             

            txtNOMCLIENT.setText(dtm.getValueAt(selectedIndex, 1).toString());
             txtPRENOMCLIENT.setText(dtm.getValueAt(selectedIndex, 2).toString());
              txtADRESSECLIENT.setText(dtm.getValueAt(selectedIndex, 3).toString());
               txtCODEPOSTALCLIENT.setText(dtm.getValueAt(selectedIndex, 4).toString());
              txtVILLECLIENT.setText(dtm.getValueAt(selectedIndex, 5).toString());
               txtPAYSCLIENT.setText(dtm.getValueAt(selectedIndex, 6).toString());
               txtTELCLIENT.setText(dtm.getValueAt(selectedIndex, 7).toString());
            txtMOBILECLIENT.setText(dtm.getValueAt(selectedIndex, 8).toString());
             txtEMAILCLIENT.setText(dtm.getValueAt(selectedIndex, 9).toString());
        
    }//GEN-LAST:event_tableClientsMouseClicked

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        // TODO add your handling code here:
          // supprimer
          DefaultTableModel dtm = (DefaultTableModel)tableClients.getModel();
     
           int selectedIndex = tableClients.getSelectedRow();
       
         int idClient = Integer.parseInt(dtm.getValueAt(selectedIndex,0).toString());
         int dialogResult  = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer cette donnée ?", "Attention",JOptionPane.YES_NO_OPTION);
       
         if (dialogResult == JOptionPane.YES_OPTION){
             
             try{
                     //ON VA SE CONNECTER A LA BASE DE DONNEES
             Class.forName("com.mysql.cj.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/xproddb", "root", "");
              
              pst = con.prepareStatement("delete from clients where IDCLIENT=?");
              
              pst.setInt(1, idClient);
              pst.executeUpdate();
              
              JOptionPane.showMessageDialog(this, "Données supprimées !");
              
                // Je vide le contenu des champs remplis 
             txtNOMCLIENT.setText("");
            txtPRENOMCLIENT.setText("");
            txtADRESSECLIENT.setText("");
            txtCODEPOSTALCLIENT.setText("");
            txtVILLECLIENT.setText("");
             txtPAYSCLIENT.setText("");
            txtTELCLIENT.setText("");
            txtMOBILECLIENT.setText("");
             txtEMAILCLIENT.setText("");
             
            tableUpdate();
              
         }    catch (ClassNotFoundException ex) {
                  Logger.getLogger(xprodDesktopAdministrateur.class.getName()).log(Level.SEVERE, null, ex);
              } catch (SQLException ex) {
                  Logger.getLogger(xprodDesktopAdministrateur.class.getName()).log(Level.SEVERE, null, ex);
              }
        }
    }//GEN-LAST:event_btnDELETEActionPerformed
            Connection con;
            PreparedStatement pst;    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDClient;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnMODIFIER1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemADDCOMMANDE;
    private javax.swing.JMenuItem jMenuItemAddFournisseur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableClients;
    private javax.swing.JTextField txtADRESSECLIENT;
    private javax.swing.JTextField txtCODEPOSTALCLIENT;
    private javax.swing.JTextField txtEMAILCLIENT;
    private javax.swing.JTextField txtMOBILECLIENT;
    private javax.swing.JTextField txtNOMCLIENT;
    private javax.swing.JTextField txtPAYSCLIENT;
    private javax.swing.JTextField txtPRENOMCLIENT;
    private javax.swing.JTextField txtTELCLIENT;
    private javax.swing.JTextField txtVILLECLIENT;
    // End of variables declaration//GEN-END:variables

    private void tableUpdate() {
        int cpt;
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/xproddb", "root", "");
        pst = con.prepareStatement("SELECT * FROM clients");// préparer la requête
        ResultSet rs = pst.executeQuery(); //Exécuter la requête SQL et la  mettre dans  la variable rs (ResultSet)
        
        ResultSetMetaData rsmd = rs.getMetaData();//Va chercher les données
        cpt = rsmd.getColumnCount();
        DefaultTableModel dtm = (DefaultTableModel)tableClients.getModel();
        dtm.setRowCount(0);
       
        while(rs.next()){ 
            Vector vect = new Vector();
            
            
           for(int i=1; i<= cpt; i++) {
                vect.add(rs.getString("IDCLIENT")); // rajouter les éléments Id dans vecteur
                 vect.add(rs.getString("NOMCLIENT"));
                   vect.add(rs.getString("PRENOMCLIENT"));
                vect.add(rs.getString("ADRESSECLIENT"));
                vect.add(rs.getString("CODEPOSTALCLIENT"));
                vect.add(rs.getString("VILLECLIENT"));
                vect.add(rs.getString("PAYSCLIENT"));
                vect.add(rs.getString("EMAILCLIENT"));
                  vect.add(rs.getString("MOBILECLIENT"));
                  
                  
              
                
            }
            
             dtm.addRow(vect);   
        }                 

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }


}
