/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.xprodswing.principal;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Axel
 */
public class Commandes extends javax.swing.JFrame {

    /**
     * Creates new form Commandes
     */
    public Commandes() {
        initComponents();
         this.setTitle("XPROD : Gestion de commandes");
       setLocationRelativeTo(null); //pour centrer le contenu de ma fenêtre
       
       tableUpdateProduit();
       tableUpdateClient();
        
          this.setTitle("XPROD : Gestion des produits");
       setLocationRelativeTo(null); //pour centrer le contenu de ma fenêtre
       tableUpdateProduit();
      
       tableUpdateClient();
    }
    public void afficherUser(String Client){
        lblUserClient.setText("Bienvenue"+Client);
    }
    //Connection
    Connection con;
    PreparedStatement pst;
    
//Mise à jour tableau
    private void tableUpdateProduit() {
        try {
            int cpt;
            try { 
                Class.forName("com.mysql.cj.jdbc.Driver");
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(XprodDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            con = DriverManager.getConnection("jdbc:mysql://localhost/xproddb","root","");
            pst = con.prepareStatement("SELECT * FROM Produits");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();
            cpt = rsmd.getColumnCount();
            DefaultTableModel dtm=(DefaultTableModel)tablePRODUIT.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
            Vector vect = new Vector();
            
            for(int i=1; i<= cpt; i++){
            vect.add(rs.getString("IDPRODUIT"));
            vect.add(rs.getString("REF"));
            vect.add(rs.getString("DESIGNATION"));
            vect.add(rs.getString("DESCRIPTIF"));
            vect.add(rs.getString("PRIXUHT"));               
            
            }
            
            dtm.addRow(vect);
            
            }
            
                    } catch (SQLException ex) { 
            Logger.getLogger(XprodDesktopAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
   
      private void tableUpdateClient() {
          try {
            int cpt;
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/xproddb","root","");
            pst = con.prepareStatement("SELECT * FROM Clients");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();
            cpt = rsmd.getColumnCount();
            DefaultTableModel dtm=(DefaultTableModel)tableCLIENT.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
                Vector vect = new Vector();
                
                for(int i=1; i<=cpt; i++){
                vect.add(rs.getString("IDCLIENT"));
                vect.add(rs.getString("PRENOMCLIENT"));
                vect.add(rs.getString("NAMECLIENT"));
                vect.add(rs.getString("ADRESSECLIENT"));
                vect.add(rs.getString("CODEPOSTALCLIENT"));
                vect.add(rs.getString("VILLECLIENT"));
                vect.add(rs.getString("PAYSCLIENT"));
                vect.add(rs.getString("TELCLIENT"));
                vect.add(rs.getString("MOBILECLIENT"));
                vect.add(rs.getString("EMAILCLIENT"));
                }
                dtm.addRow(vect); 
            }
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListeClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ListeClient.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePRODUIT = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCLIENT = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPRENOMCLIENT = new javax.swing.JTextField();
        txtNameClient = new javax.swing.JTextField();
        txtREFCLIENT = new javax.swing.JTextField();
        txtDESIGNATIONCLIENT = new javax.swing.JTextField();
        txtDESCRIPTIFCLIENT = new javax.swing.JTextField();
        txtPRIXUHTCLIENT = new javax.swing.JTextField();
        txtQTECLIENT = new javax.swing.JTextField();
        txtPRIXTHTCLIENT = new javax.swing.JTextField();
        btnCREATEBILL = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblUserClient = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBILL = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFRAISPORT = new javax.swing.JTextField();
        txtTVACLIENT = new javax.swing.JTextField();
        txtPRIXTTCCLIENT = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCOMMANDE = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(50, 8, 16));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTE DES PRODUITS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10), new java.awt.Color(255, 255, 204))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(255, 255, 204));
        jPanel6.setToolTipText("");

        tablePRODUIT.setBackground(new java.awt.Color(0, 0, 0));
        tablePRODUIT.setForeground(new java.awt.Color(255, 255, 204));
        tablePRODUIT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUIT", "REF", "DESIGNATION", "DESCRIPTIF", "PRIX UHT"
            }
        ));
        tablePRODUIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePRODUITMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePRODUIT);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(50, 8, 16));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTE DES CLIENTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10), new java.awt.Color(255, 255, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));

        tableCLIENT.setBackground(new java.awt.Color(0, 0, 0));
        tableCLIENT.setForeground(new java.awt.Color(255, 255, 204));
        tableCLIENT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID CLIENT", "PRENOM", "NOM", "ADRESSE", "CP", "VILLE", "PAYS", "TEL", "MOBILE", "EMAIL"
            }
        ));
        tableCLIENT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCLIENTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCLIENT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );

        jPanel3.setBackground(new java.awt.Color(50, 8, 16));
        jPanel3.setForeground(new java.awt.Color(255, 255, 204));

        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("PRENOM CLIENT :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("NOM CLIENT :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("REF :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("DESIGNATION :");

        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("DECRIPTIF :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("PRIX UHT :");

        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("QTE :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("PRIX THT :");

        txtPRIXTHTCLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPRIXTHTCLIENTActionPerformed(evt);
            }
        });

        btnCREATEBILL.setBackground(new java.awt.Color(0, 0, 0));
        btnCREATEBILL.setForeground(new java.awt.Color(255, 255, 204));
        btnCREATEBILL.setText("Créer la facture");
        btnCREATEBILL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCREATEBILLActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 204));
        jButton3.setText("Imprimer la facture");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPRENOMCLIENT)
                            .addComponent(txtNameClient)
                            .addComponent(txtREFCLIENT)
                            .addComponent(txtDESIGNATIONCLIENT)
                            .addComponent(txtDESCRIPTIFCLIENT)
                            .addComponent(txtPRIXUHTCLIENT)
                            .addComponent(txtQTECLIENT)
                            .addComponent(txtPRIXTHTCLIENT, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCREATEBILL)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPRENOMCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtREFCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDESIGNATIONCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDESCRIPTIFCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPRIXUHTCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtQTECLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtPRIXTHTCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCREATEBILL)
                    .addComponent(jButton3))
                .addGap(56, 56, 56))
        );

        jPanel2.setBackground(new java.awt.Color(50, 8, 16));
        jPanel2.setForeground(new java.awt.Color(255, 255, 204));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Listes des commandes");

        lblUserClient.setBackground(new java.awt.Color(0, 0, 0));
        lblUserClient.setForeground(new java.awt.Color(255, 255, 204));
        lblUserClient.setText("Client");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblUserClient, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserClient, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtBILL.setColumns(20);
        txtBILL.setRows(5);
        jScrollPane4.setViewportView(txtBILL);

        jPanel5.setBackground(new java.awt.Color(50, 8, 16));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COMMANDES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10), new java.awt.Color(255, 255, 204))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 204));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("FRAIS DE PORT :");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("T.V.A :");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("PRIX TOTAL TTC :");

        tableCOMMANDE.setBackground(new java.awt.Color(0, 0, 0));
        tableCOMMANDE.setForeground(new java.awt.Color(255, 255, 204));
        tableCOMMANDE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUIT", "REF", "DESIGNATION", "DESCRIPTIF", "PRIX UHT", "QTE", "PRIX THT"
            }
        ));
        jScrollPane3.setViewportView(tableCOMMANDE);
        if (tableCOMMANDE.getColumnModel().getColumnCount() > 0) {
            tableCOMMANDE.getColumnModel().getColumn(0).setHeaderValue("ID PRODUIT");
            tableCOMMANDE.getColumnModel().getColumn(1).setHeaderValue("REF");
            tableCOMMANDE.getColumnModel().getColumn(2).setHeaderValue("DESIGNATION");
            tableCOMMANDE.getColumnModel().getColumn(3).setHeaderValue("DESCRIPTIF");
            tableCOMMANDE.getColumnModel().getColumn(4).setHeaderValue("PRIX UHT");
            tableCOMMANDE.getColumnModel().getColumn(5).setHeaderValue("QTE");
            tableCOMMANDE.getColumnModel().getColumn(6).setHeaderValue("PRIX THT");
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txtTVACLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtPRIXTTCCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFRAISPORT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTVACLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFRAISPORT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPRIXTTCCLIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(25, 25, 25))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1429, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePRODUITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePRODUITMouseClicked
double sum = 0.0;
double totalTTC = 0.0;
double prixTVA= 0.0;
DefaultTableModel dtm = (DefaultTableModel)tablePRODUIT.getModel();
int selectedIndex = tablePRODUIT.getSelectedRow();

//Préremplir les champs de texte
txtREFCLIENT.setText(dtm.getValueAt(selectedIndex, 1).toString());
txtDESIGNATIONCLIENT.setText(dtm.getValueAt(selectedIndex, 2).toString());
txtDESCRIPTIFCLIENT.setText(dtm.getValueAt(selectedIndex, 3).toString());
txtPRIXUHTCLIENT.setText(dtm.getValueAt(selectedIndex, 4).toString());

//Ajout dans la table des commandes
String idCLIENT = dtm.getValueAt(selectedIndex, 0).toString();
String txtREFCLIENT = dtm.getValueAt(selectedIndex, 1).toString();
String txtDESIGNATIONCLIENT = dtm.getValueAt(selectedIndex, 2).toString();
String txtDESCRIPTIFCLIENT = dtm.getValueAt(selectedIndex, 3).toString();
double txtPRIXUHTCLIENT = Double.parseDouble(dtm.getValueAt(selectedIndex, 4).toString());

int qte = Integer.parseInt(JOptionPane.showInputDialog(null,"Entrez la quantité !"));

double tot = txtPRIXUHTCLIENT * qte;
double fraisPort = Integer.parseInt(JOptionPane.showInputDialog(null,"Entrez les frais de port !"));
int tva = Integer.parseInt(JOptionPane.showInputDialog(null,"Entrez la TVA !"));
dtm = (DefaultTableModel)tableCOMMANDE.getModel();



dtm.addRow(new Object[]
{
idCLIENT,
txtREFCLIENT,
txtDESIGNATIONCLIENT,
txtDESCRIPTIFCLIENT,
txtPRIXUHTCLIENT,
qte,
tot
}
);

for(double i=0; i<tableCOMMANDE.getRowCount(); i++)
{
  sum = fraisPort + sum + Double.parseDouble(tableCOMMANDE.getValueAt((int)i, 6).toString());
  prixTVA = sum*tva/100;
  totalTTC = sum + sum*tva/100;
}
txtPRIXTTCCLIENT.setText(Double.toString(totalTTC));
txtQTECLIENT.setText(Integer.toString(qte));
txtPRIXTHTCLIENT.setText(Double.toString(tot));
txtFRAISPORT.setText(Double.toString(fraisPort));
txtTVACLIENT.setText(Double.toString(prixTVA));



    }//GEN-LAST:event_tablePRODUITMouseClicked

    private void txtPRIXTHTCLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPRIXTHTCLIENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRIXTHTCLIENTActionPerformed

    private void tableCLIENTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCLIENTMouseClicked
DefaultTableModel dtm=(DefaultTableModel)tableCLIENT.getModel();
        int selectedIndex = tableCLIENT.getSelectedRow();
        
            txtPRENOMCLIENT.setText(dtm.getValueAt (selectedIndex, 1).toString());
            txtNameClient.setText(dtm.getValueAt (selectedIndex, 2).toString());    }//GEN-LAST:event_tableCLIENTMouseClicked

    private void btnCREATEBILLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCREATEBILLActionPerformed
        //Create bill
        double totalTTC = Double.parseDouble(txtPRIXTTCCLIENT.getText());
        double tva = Double.parseDouble(txtTVACLIENT.getText());
        double fraisPORT = Double.parseDouble(txtFRAISPORT.getText());
        String prenomClient = txtPRENOMCLIENT.getText();
        String nomClient = txtNameClient.getText();
        
        DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel) tableCOMMANDE.getModel();
        
        txtBILL.setText(txtBILL.getText() +"***************************************************************************************************************************\n");
        txtBILL.setText(txtBILL.getText() +"                                                   FACTURE XPROD                                                               \n");
        txtBILL.setText(txtBILL.getText() +"***************************************************************************************************************************\n");
                //Names
        txtBILL.setText(txtBILL.getText() + "\t" + "\t" + "Prénom du client :" + prenomClient + "\n");
        txtBILL.setText(txtBILL.getText() + "\t" + "\t" + "Nom du client :" + nomClient + "\n");
                
       //Heading
       txtBILL.setText(txtBILL.getText() +  "REF" + "\t" + "DESIGNATION" + "\t" + "DESCRIPTIF" + "\t" + "PRIX UHT" + "\t" + "QTE" + "\t" + "PRIXTHT" + "\n");   
       
       for(int i = 0; i < model.getRowCount(); i++)
       {
           String ref = (String)model.getValueAt(i, 1);
           String design = (String)model.getValueAt(i, 2);
           String descr = (String)model.getValueAt(i, 3);
           
           double prixU = (double)model.getValueAt(i, 4);
           int qte =(int)model.getValueAt(i, 5);
           double prixTHT = (double)model.getValueAt(i, 6);
           
           
           txtBILL.setText(txtBILL.getText() + ref + "\t" + design + "\t" + descr + "\t" + prixU + "\t" + qte + "\t" + prixTHT + "\n");
           
       }
       
       txtBILL.setText(txtBILL.getText() + "\n");
       
       txtBILL.setText(txtBILL.getText() + "\t" + "\t" +"Frais port"+ fraisPORT + "\n" );
       txtBILL.setText(txtBILL.getText() + "\t" + "\t" +"TVA"+ tva + "\n" );
       txtBILL.setText(txtBILL.getText() + "\t" + "\t" +"Total TTC"+ totalTTC + "\n" );
       txtBILL.setText(txtBILL.getText() + "\n" );
       txtBILL.setText(txtBILL.getText() + "*****************************************************\n" );
       txtBILL.setText(txtBILL.getText() + "           MERCI POUR VOTRE VISITE ! A BIENTOT                    \n" );

       
    }//GEN-LAST:event_btnCREATEBILLActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            //Print bill
            boolean complete = txtBILL.print();
            
            if(complete){
                JOptionPane.showMessageDialog(null,"Impression faite!","Message",JOptionPane.INFORMATION_MESSAGE);
                
            }else {
                JOptionPane.showMessageDialog(null, "Impression en cours...!","Imprimante",JOptionPane.ERROR_MESSAGE);
                
            } } catch (PrinterException ex) {
            Logger.getLogger(Commandes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commandes().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCREATEBILL;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblUserClient;
    private javax.swing.JTable tableCLIENT;
    private javax.swing.JTable tableCOMMANDE;
    private javax.swing.JTable tablePRODUIT;
    private javax.swing.JTextArea txtBILL;
    private javax.swing.JTextField txtDESCRIPTIFCLIENT;
    private javax.swing.JTextField txtDESIGNATIONCLIENT;
    private javax.swing.JTextField txtFRAISPORT;
    private javax.swing.JTextField txtNameClient;
    private javax.swing.JTextField txtPRENOMCLIENT;
    private javax.swing.JTextField txtPRIXTHTCLIENT;
    private javax.swing.JTextField txtPRIXTTCCLIENT;
    private javax.swing.JTextField txtPRIXUHTCLIENT;
    private javax.swing.JTextField txtQTECLIENT;
    private javax.swing.JTextField txtREFCLIENT;
    private javax.swing.JTextField txtTVACLIENT;
    // End of variables declaration//GEN-END:variables
 
    
    
    
    }


